### ISSUE TITLE
Clean up DLEQ notation, adopt that of PrivacyPass

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-sullivan-cfrg-voprf#3]
r & \gets \mathbb{Z}_p \\
A &= rG \\
B &= rM \\
c &= H(G,Y,Z,A,B) \\
s &= (r - ck) (\text{mod} p) \\
& \mathsf{Output } \; (c, s) 

A' &= sG + cY \\
B' &= sM + cZ \\
c' &= H(G,Y,Z,A',B') \\
& \mathsf{Output } \; c == c'

\log_G(Y) =? \log_M(Z)
Y = kG, Z = kM

\mathsf{DLEQVerify}(G, Y, M, Z, (c, s))

\mathsf{DLEQGenerate}(G, Y, M, Z)

**Comment by alxdavids** [comment]
I'm happy to have a go at doing this

**Comment by chris-wood** [comment]
Fixed by #9.
