### ISSUE TITLE
Add "parameter commitment" support

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-sullivan-cfrg-voprf#5]
In some cases, it may be desirable for P to force V to only redeem its PRF value for specific set of "parameters." For example, imagine P and V could use the PRF output to derive an encryption key for encrypting data to the server, though V is free to use whatever encryption algorithm it likes. V tells P which algorithm it's using in its redemption+data message to P. Currently, P cannot restrict the algorithm V uses since the only thing P commits to is the keying material during the VOPRF protocol. 

One way to address this problem is as follows. Let _params_ be the parameters that P wishes V to use when redeeming its PRF value. (In the example above, it might be a canonical representation of the encryption algorithm cipher suite.) When multiplying V's blinded message M by its scalar, P also mixes in t = H(_params_ || k2), where k2 is another secret scalar != k, and H is a full-domain hash function that maps to curve base field (e.g., Z_p). The resulting blinded and "signed" message is then Z = tkM = rkrX. 

When redeeming the PRF value, V supplies the PRF input *and* _params_. P can then recompute t as above and mix it into the computation. Moreover, since t is computed by appending a secret to the parameters and hashing the result, V cannot remove it from Z without knowledge of k2.

**Comment by chris-wood** [comment]
Alternatively: Have a separate public set of commitments for each param value published somewhere and return the current VOPRF value plus a DLEQ with respect to the committed value.

**Comment by alxdavids** [comment]
I'm not certain on how providing a DLEQ proof wrt the params forces V to redeem PRF values wrt these same params. The DLEQ proof certainly cannot be verified without using the same params, but it seems like the blinded tokens should also be signed in such a way that the params are implicitly embedded as in the first idea.

Maybe I am mistaken though?

**Comment by chris-wood** [comment]
Closed by #7.
